#!/usr/bin/env python3
"""
build_camera_extrinsics.py
=============================================================================
Rebuild calibration/camera_extrinsics.py using command-line arguments.

This output file is used by:
    - sground.py                (line/tape ground projection)
    - scamera_extrinsics.py     (ArUco world-pose recovery)

Mount parameters
----------------
    pitch (deg)  : camera tilt relative to the robot's horizontal plane
                   (positive means the camera is looking down at the floor)
    roll  (deg)  : sideways tilt around the camera's forward axis
                   (positive means the camera is leaning to the right)
    yaw   (deg)  : heading offset relative to the robot's forward direction
                   (positive means the camera is pointing to the left)
    tx, ty, tz   : camera optical centre position in the robot body frame
                   (forward / left / up), measured in metres.

Measure pitch and roll once with a phone level placed on the camera housing.
Measure tx, ty and tz with a ruler from the robot origin, which is the centre
of the wheelbase at ground level, to the camera lens.

Usage
-----
    python build_camera_extrinsics.py                        # print current values
    python build_camera_extrinsics.py --pitch 25 --tz 0.235  # update only listed fields
    python build_camera_extrinsics.py --pitch 12 --roll 0 --yaw 0 \
                                       --tx 0.05 --ty 0 --tz 0.22
"""
from __future__ import annotations
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.join(HERE, "camera_extrinsics.py")


def _read_existing() -> dict:
    """Read the current values from camera_extrinsics.py, if the file exists."""
    sys.path.insert(0, HERE)
    try:
        import camera_extrinsics as ce  # type: ignore
        return dict(
            pitch=getattr(ce, "CAMERA_TILT_DEG",   25.0),
            roll =getattr(ce, "CAMERA_ROLL_DEG",   0.0),
            yaw  =getattr(ce, "CAMERA_YAW_DEG",    0.0),
            tx   =getattr(ce, "CAMERA_X_OFFSET_M", 0.02),
            ty   =getattr(ce, "CAMERA_Y_OFFSET_M", -0.005),
            tz   =getattr(ce, "CAMERA_HEIGHT_M",   0.185),
        )
    except ImportError:
        return dict(pitch=25.0, roll=0.0, yaw=0.0, tx=0.02, ty=-0.005, tz=0.185)


def _write(values: dict) -> None:
    body = (
        '"""Camera mount parameters for the robot.\n'
        '\n'
        'Generated by calibration/build_camera_extrinsics.py.\n'
        'To update these values, edit this file manually or run the script again.\n'
        '\n'
        'Frame: robot body  (+X = forward, +Y = left, +Z = up).\n'
        '"""\n'
        '\n'
        f'CAMERA_HEIGHT_M   = {values["tz"]:.4f}   # height of the camera optical centre above ground (m)\n'
        f'CAMERA_TILT_DEG   = {values["pitch"]:.2f}    # nose-down pitch angle (deg, +)\n'
        f'CAMERA_ROLL_DEG   = {values["roll"]:.2f}    # sideways roll angle (deg, +)\n'
        f'CAMERA_YAW_DEG    = {values["yaw"]:.2f}    # heading offset angle (deg, +)\n'
        f'CAMERA_X_OFFSET_M = {values["tx"]:.4f}   # forward offset of the camera centre (m)\n'
        f'CAMERA_Y_OFFSET_M = {values["ty"]:.4f}  # left offset of the camera centre (m)\n'
    )
    with open(TARGET, "w") as f:
        f.write(body)


def main() -> int:
    cur = _read_existing()
    p = argparse.ArgumentParser(description="Update calibration/camera_extrinsics.py")
    p.add_argument("--pitch", type=float, default=cur["pitch"], help="camera pitch angle (deg, nose-down +)")
    p.add_argument("--roll",  type=float, default=cur["roll"],  help="camera roll angle (deg, leaning right +)")
    p.add_argument("--yaw",   type=float, default=cur["yaw"],   help="camera yaw angle (deg, turned left +)")
    p.add_argument("--tx",    type=float, default=cur["tx"],    help="X offset in the robot frame (m, forward +)")
    p.add_argument("--ty",    type=float, default=cur["ty"],    help="Y offset in the robot frame (m, left +)")
    p.add_argument("--tz",    type=float, default=cur["tz"],    help="Z offset in the robot frame (m, up +)")
    p.add_argument("--show",  action="store_true",              help="show current values without writing")
    args = p.parse_args()

    new = dict(pitch=args.pitch, roll=args.roll, yaw=args.yaw,
               tx=args.tx,       ty=args.ty,     tz=args.tz)

    if args.show:
        print("% Current calibration/camera_extrinsics.py:")
        for k, v in cur.items():
            print(f"   {k:>5} = {v}")
        return 0

    _write(new)
    print(f"% wrote {TARGET}")
    print("% values:")
    for k, v in new.items():
        print(f"   {k:>5} = {v}")
    return 0


if __name__ == "__main__":
    sys.exit(main())