#!/usr/bin/env python3
"""
test_sline_tuner.py
=============================================================================
Live tuner for sline tape-detection thresholds.

Connects to the robot's MJPEG stream, runs SLine.process() each frame and
overlays the debug view together with the editable parameter list. Use the
keyboard to navigate, change values, and persist them.

Usage
-----
    python test_sline_tuner.py --host 10.197.216.254
    python test_sline_tuner.py --host 10.197.216.254 --port 7123

Controls
--------
    UP / DOWN     move the cursor between parameters
    LEFT / RIGHT  decrease / increase the highlighted parameter
    + / -         shift+arrow alternative for systems without arrow keys
    [ / ]         coarse step (10× normal)
    R             reset to last-saved (file) values
    P             print current parameters to terminal
    S             save current values to calibration/sline_thresholds.py
    L             active branch = 0   (left)
    K             active branch = 1   (right)
    Q  /  ESC     quit
"""
from __future__ import annotations
import argparse
import os
import sys
import time
from typing import List, Tuple

import cv2
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from perception.camera.sline import vision  # noqa: E402  (import order matters: sline pulls thresholds first)


# ---------------------------------------------------------------------------
# Parameter table.
#
# (display_name, attr_lowercase, kind, fine_step, coarse_step, min, max)
# kind: 'int' | 'float'
PARAMS: List[Tuple[str, str, str, float, float, float, float]] = [
    # Group A — colour mask
    ("WHITE_V_MIN",            "white_v_min",            "int",   1,    10,   0,    255),
    ("WHITE_S_MAX",            "white_s_max",            "int",   1,    10,   0,    255),
    # Group B — ROI / strip search
    ("LINE_ROI_TOP_FRAC",      "line_roi_top_frac",      "float", 0.01, 0.05, 0.0,  1.0),
    ("N_STRIPS",               "n_strips",               "int",   1,    2,    2,    32),
    ("MIN_BLOB_AREA",          "min_blob_area",          "int",   10,   50,   0,    5000),
    ("INIT_WINDOW_PX",         "init_window_px",         "int",   10,   40,   20,   800),
    ("TRACK_WINDOW_PX",        "track_window_px",        "int",   10,   40,   20,   800),
    ("TAPE_VERIFY_MARGIN_PX",  "tape_verify_margin_px",  "int",   1,    5,    0,    50),
    # Group C — fork detection
    ("FORK_SEARCH_STRIPS",     "fork_search_strips",     "int",   1,    2,    1,    16),
    ("FORK_MIN_SEP_PX",        "fork_min_sep_px",        "int",   1,    10,   0,    300),
    ("FORK_MIN_GROUND_SEP_M",  "fork_min_ground_sep_m",  "float", 0.005, 0.05, 0.0, 1.0),
    ("FORK_CANDIDATE_MIN",     "fork_candidate_min",     "int",   1,    2,    1,    32),
    ("FORK_CONFIRMED_MIN",     "fork_confirmed_min",     "int",   1,    2,    1,    32),
    # Group D — validity
    ("MIN_VALID_STRIPS",       "min_valid_strips",       "int",   1,    2,    1,    32),
]

THRESHOLDS_PATH = os.path.join(HERE, "calibration", "sline_thresholds.py")


# ---------------------------------------------------------------------------
def read_param_value(name: str):
    """Read the live value of a parameter from sline's module globals."""
    from perception.camera import sline
    return getattr(sline, name)


def write_param_value(name_lower: str, value):
    """Push a value back into sline (both instance attr and module global)."""
    vision.apply_thresholds(**{name_lower: value})


def clamp(value, lo, hi, kind):
    if kind == "int":
        return int(max(lo, min(hi, round(value))))
    return float(max(lo, min(hi, value)))


def step(value, delta, lo, hi, kind):
    return clamp(value + delta, lo, hi, kind)


# ---------------------------------------------------------------------------
def save_to_file():
    """Re-write calibration/sline_thresholds.py with the current live values."""
    lines = [
        '"""Tape detection thresholds for sline.SLine.\n',
        '\n',
        'Auto-generated by test_sline_tuner.py (press S in the live tuner).\n',
        'Edit by hand if needed; values are read at sline.py import time.\n',
        '"""\n',
        '\n',
    ]

    groups = [
        ("# --- A: colour mask ---------------------------------------------------------",
         ("WHITE_V_MIN", "WHITE_S_MAX")),
        ("# --- B: ROI / strip search --------------------------------------------------",
         ("LINE_ROI_TOP_FRAC", "N_STRIPS", "MIN_BLOB_AREA",
          "INIT_WINDOW_PX", "TRACK_WINDOW_PX", "TAPE_VERIFY_MARGIN_PX")),
        ("# --- C: fork (Y / T) detection ----------------------------------------------",
         ("FORK_SEARCH_STRIPS", "FORK_MIN_SEP_PX", "FORK_MIN_GROUND_SEP_M",
          "FORK_CANDIDATE_MIN", "FORK_CONFIRMED_MIN")),
        ("# --- D: line validity -------------------------------------------------------",
         ("MIN_VALID_STRIPS",)),
    ]

    for header, names in groups:
        lines.append(header + "\n")
        for n in names:
            v = read_param_value(n)
            if isinstance(v, float):
                lines.append(f"{n:<22} = {v:.4f}\n")
            else:
                lines.append(f"{n:<22} = {v}\n")
        lines.append("\n")

    os.makedirs(os.path.dirname(THRESHOLDS_PATH), exist_ok=True)
    with open(THRESHOLDS_PATH, "w") as f:
        f.writelines(lines)
    print(f"% SAVED -> {THRESHOLDS_PATH}")


def load_from_file_into_runtime():
    """Re-import sline_thresholds.py and push the values into the live SLine."""
    import importlib
    try:
        import calibration.sline_thresholds as st
        importlib.reload(st)
    except ImportError:
        print("% sline_thresholds.py not found — keeping current values.")
        return
    kwargs = {}
    for _, attr, _, _, _, _, _ in PARAMS:
        upper = attr.upper()
        if hasattr(st, upper):
            kwargs[attr] = getattr(st, upper)
    write_param_value_bulk(kwargs)
    print("% RESET to file values.")


def write_param_value_bulk(d: dict):
    vision.apply_thresholds(**d)


# ---------------------------------------------------------------------------
def draw_panel(frame, cursor_idx, status_msg=""):
    """Overlay parameter list + status onto the debug frame."""
    h, w = frame.shape[:2]

    panel_w = 360
    panel = np.zeros((h, panel_w, 3), dtype=np.uint8)

    cv2.putText(panel, "SLINE TUNER", (10, 22),
                cv2.FONT_HERSHEY_PLAIN, 1.3, (0, 220, 255), 2)
    cv2.putText(panel, "[arrows] move/adjust  [+/-] adjust  [ ] coarse",
                (10, 42), cv2.FONT_HERSHEY_PLAIN, 0.85, (180, 180, 180), 1)
    cv2.putText(panel, "[S]ave  [R]eset  [P]rint  [L]eft  [K]right  [Q]uit",
                (10, 58), cv2.FONT_HERSHEY_PLAIN, 0.85, (180, 180, 180), 1)

    y = 86
    for i, (name, attr, kind, _, _, _, _) in enumerate(PARAMS):
        v = read_param_value(name)
        sel = (i == cursor_idx)
        bg = (40, 80, 40) if sel else (0, 0, 0)
        fg = (0, 255, 200) if sel else (220, 220, 220)
        cv2.rectangle(panel, (4, y - 14), (panel_w - 4, y + 4), bg, -1)
        if isinstance(v, float):
            text = f"{name:<22} {v:.4f}"
        else:
            text = f"{name:<22} {v}"
        cv2.putText(panel, text, (10, y),
                    cv2.FONT_HERSHEY_PLAIN, 0.95, fg, 1)
        y += 22

    # live status from sline (fork state)
    y += 6
    cv2.line(panel, (4, y), (panel_w - 4, y), (60, 60, 60), 1)
    y += 18
    cv2.putText(panel, f"line_valid     : {bool(vision.line_valid)}",
                (10, y), cv2.FONT_HERSHEY_PLAIN, 0.95, (180, 220, 180), 1); y += 18
    cv2.putText(panel, f"fork_candidate : {bool(vision.fork_candidate)}",
                (10, y), cv2.FONT_HERSHEY_PLAIN, 0.95, (180, 220, 180), 1); y += 18
    cv2.putText(panel, f"fork_confirmed : {bool(vision.fork_confirmed)}",
                (10, y), cv2.FONT_HERSHEY_PLAIN, 0.95, (180, 220, 180), 1); y += 18
    cv2.putText(panel, f"fork_evidence  : {int(vision.fork_evidence)}",
                (10, y), cv2.FONT_HERSHEY_PLAIN, 0.95, (180, 220, 180), 1); y += 18
    cv2.putText(panel, f"branch         : {int(vision.active_branch)}",
                (10, y), cv2.FONT_HERSHEY_PLAIN, 0.95, (180, 220, 180), 1); y += 18

    if status_msg:
        cv2.putText(panel, status_msg, (10, h - 20),
                    cv2.FONT_HERSHEY_PLAIN, 1.0, (0, 220, 255), 1)

    out = np.zeros((h, w + panel_w, 3), dtype=np.uint8)
    out[:, :w] = frame
    out[:, w:] = panel
    return out


# ---------------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(description="Live sline threshold tuner")
    parser.add_argument("--host",   default="localhost")
    parser.add_argument("--port",   type=int, default=7123)
    parser.add_argument("--params", default="../calibration/camera_params.npz")
    args = parser.parse_args()

    vision.setup(args.params, debug=True)
    if not vision.ready:
        print("% Setup failed.")
        return 1

    stream_url = f"http://{args.host}:{args.port}/stream.mjpg"
    print(f"% Connecting to {stream_url} ...")
    cap = cv2.VideoCapture(stream_url)
    cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)
    if not cap.isOpened():
        print(f"% ERROR: could not open {stream_url}")
        return 1

    cursor = 0
    status = ""
    status_until = 0.0

    print("% Tuner ready. Press S to save, Q to quit.")

    while True:
        ret, frame = cap.read()
        if not ret:
            time.sleep(0.05)
            continue

        vision.process(frame)
        debug = vision.debug_frame if vision.debug_frame is not None else frame
        if status and time.time() > status_until:
            status = ""
        out = draw_panel(debug, cursor, status)
        cv2.imshow("sline tuner", out)

        # waitKeyEx returns full key code (incl. arrows on macOS/Linux)
        key = cv2.waitKeyEx(1) & 0xFFFFFF
        if key == 0xFFFFFF or key == 0xFF:
            continue

        # Map to a small command vocabulary
        # Arrow codes vary by OS; cv2 returns 0x10000 on Linux, 63232+ on macOS.
        UP    = (82, 65362, 0xF700, 2490368)
        DOWN  = (84, 65364, 0xF701, 2621440)
        LEFT  = (81, 65361, 0xF702, 2424832)
        RIGHT = (83, 65363, 0xF703, 2555904)

        coarse = False
        if key == ord('q') or key == 27:
            break
        elif key in UP:
            cursor = (cursor - 1) % len(PARAMS)
        elif key in DOWN:
            cursor = (cursor + 1) % len(PARAMS)
        elif key == ord('['):
            coarse = True; key_dir = -1
        elif key == ord(']'):
            coarse = True; key_dir = +1
        elif key in LEFT or key == ord('-'):
            key_dir = -1
        elif key in RIGHT or key in (ord('+'), ord('=')):
            key_dir = +1
        elif key == ord('s') or key == ord('S'):
            save_to_file()
            status = "SAVED"; status_until = time.time() + 1.5
            continue
        elif key == ord('r') or key == ord('R'):
            load_from_file_into_runtime()
            status = "RESET to file"; status_until = time.time() + 1.5
            continue
        elif key == ord('p') or key == ord('P'):
            print("\n-- current values --")
            for name, _, _, _, _, _, _ in PARAMS:
                print(f"   {name:<22} {read_param_value(name)}")
            continue
        elif key == ord('l') or key == ord('L'):
            vision.set_active_branch(0); continue
        elif key == ord('k') or key == ord('K'):
            vision.set_active_branch(1); continue
        else:
            continue

        # Apply adjustment
        name, attr, kind, fine, coarse_step, lo, hi = PARAMS[cursor]
        delta = (coarse_step if coarse else fine) * key_dir
        new_v = step(read_param_value(name), delta, lo, hi, kind)
        write_param_value(attr, new_v)

    cap.release()
    cv2.destroyAllWindows()
    return 0


if __name__ == "__main__":
    sys.exit(main())
